### ISSUE TITLE
No 'Authorization: Basic' header found.

### ISSUE THREAD

**Issue by zygeilit** [halverneus/static-file-server#11]
Error message is "No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured", need configs?

**Comment by halverneus** [comment]
At the moment, Basic Authentication isn't officially supported and is not implemented at all on the master branch. There is a branch that has a proposal for the feature, but it isn't ready for use, yet. Having said that, there are a couple of ways Basic Authentication is implemented and the basic_auth branch only supports one. For example, using wget requires an extra parameter (from the 'static-file-server help' command):

wget --user 'user' --password 'pass' --auth-no-challenge https://my.machine/my.file
