### ISSUE TITLE
Show Logs?

### ISSUE THREAD

**Issue by haydenth** [halverneus/static-file-server#13]
When I start this container and view files in my browser it shows
```
Attaching to fileserver
```

And then nothing further.

Is there anyway to have it output simple access logs? I run this with `docker-compose` and having some kind of log output would help me debug client-server issues on the client side.

I love this project, by the way. It's surprisingly hard to find a super simple and tiny docker container for serving up files.

**Comment by haydenth** [comment]
that would be PERFECT!

**Comment by halverneus** [comment]
The feature is now available in v1.4.0. It can be enabled with the DEBUG environment variable (DEBUG=true). Thanks for the feedback!

**Comment by haydenth** [comment]
Thank you!!
