### ISSUE TITLE
How to pass the configurations?

### ISSUE THREAD

**Issue by symoN5** [halverneus/static-file-server#30]
The documentation says: "Pass in the path to the configuration file using the command line option ('-c', '-config', '--config')." But I don't get it. Where to add this command line option? Is this a docker thing?

Like: 

> docker run -d \
>     -v /my/folder:/web \
>     -p 8080:8080 \
>     -c config.yaml
>     halverneus/static-file-server:latest

**Comment by halverneus** [comment]
It gets passed to the executable, itself. If you are not using Docker:
static-file-server -c /path/to/config.yml

If using Docker:
docker run -d -v /my/folder:/web -v /my/config.yml:/config.yml -p 8080:8080 halverneus/static-file-server:latest -c config.yml

Having said that, if you are using Docker, it is generally preferable to use the environment variables.

**Comment by symoN5** [comment]
Ahh, now I'm getting it, thank you! This works perfect!
