### ISSUE TITLE
CORS-support

### ISSUE THREAD

**Issue by giovanniborella** [halverneus/static-file-server#35]
Is it just me, or does this not support CORS?

**Comment by halverneus** [comment]
It doesn't, but if that is a feature you are looking for, it should be fairly simple to add. I see someone already forked this repository to add CORS ( https://github.com/Lxy0415/static-file-server/commit/66a68705e8b9d103d9bfa79a0506b75a1c415bc8 ). They haven't created a pull request for the feature, yet. Try it out and report here if the implementation works for your needs. If it works I'll see about getting it added in. If it doesn't, let me know what doesn't work from Lxy0415's implementation and I'll see what I can do about it.
