### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by neonerd0** [halverneus/static-file-server#46]
I'm trying to setup static-file-server via docker and made the following envlist file:
```
# envlist

CORS=true
PORT=8080
SHOW_LISTING=true
FOLDER=/web
```

I ran with the docker command:
```
sudo docker container run -v /home/demouser/tools/fileshare:/web -p 8080:8080 --env-file envlist halverneus/static-file-server:latest
```

But when I access through a remote to the domain `10.0.0.105:8080` I get 403 forbidden. I also cannot access any file content through the domain.
I've tried `chmod` on the folder contents but it didn't work as well.

Any tips?

**Comment by halverneus** [comment]
The only Forbidden that the code explicitly returns is when the environment variable "REFERRERS" is set. Otherwise, I can only see it as a file permission issue. I'm not suggesting for a long-term solution, but just a troubleshooting step, what do you get when you "chmod -R 0777 /home/demouser/tools/fileshare"?

**Comment by neonerd0** [comment]
Still getting 403 forbidden if I chmod the entire folder and its contents. Is there a way for me to ssh into the container and inspect the volume?

**Comment by neonerd0** [comment]
This is the following output from the fileserver:

```
Using the following configuration:
cors: true
debug: true
folder: /web
host: ""
port: 8080
show-listing: true
tls-cert: ""
tls-key: ""
url-prefix: ""
referrers: []

2020/03/19 07:07:03 REQ from '10.0.196.18:57780': GET HTTP/1.1 10.0.1.123:8080/testdir -> /web/testdir
```

The response is 403 for all files in `FOLDER`

**Comment by neonerd0** [comment]
I've resolved this issue by reinstalling docker-ce for centos

```
> sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
> sudo dnf list docker-ce
> sudo dnf install docker-ce --nobest -y
> systemctl start docker
> systemctl enable docker

```
