### ISSUE TITLE
Can static-file-server disable TLSv1.0 and TLSv1.1.  Only allow  TLSv1.2 and TLSv1.3?

### ISSUE THREAD

**Issue by airbadboy-victor** [halverneus/static-file-server#62]
Hello guys !
I want start the static-file-server by the command below:

> _docker service create --name https-server --secret hub_WEBSERVER_CUSTOM_CERT_FILE --secret hub_WEBSERVER_CUSTOM_KEY_FILE --env-file envlist -p "8448:8448" --mount type=bind,source=/home/siguser/https-server,target=/web halverneus/static-file-server:latest

And it will all the version of TLS protocol. As I use the command below to verify it.

> **_curl -vk --tlsv1.0 https://localhost:8448_**

> * Rebuilt URL to: https://localhost:8448/

> *   Trying 127.0.0.1...
> * TCP_NODELAY set
> * Connected to localhost (127.0.0.1) port 8448 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/certs/ca-certificates.crt
>   CApath: /etc/ssl/certs
> * TLSv1.0 (OUT), TLS handshake, Client hello (1):
> * TLSv1.0 (IN), TLS handshake, Server hello (2):
> * TLSv1.0 (IN), TLS handshake, Certificate (11):
> * TLSv1.0 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.0 (IN), TLS handshake, Server finished (14):
> * TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.0 (OUT), TLS change cipher, Client hello (1):
> * TLSv1.0 (OUT), TLS handshake, Finished (20):
> * TLSv1.0 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.0 / ECDHE-RSA-AES128-SHA
> * ALPN, server accepted to use h2
> * Server certificate:
> *  subject: C=CN; ST=Some-State; O=Internet Widgits Pty Ltd; CN=localhost
> *  start date: Jun  4 13:44:58 2021 GMT
> *  expire date: Jul  4 13:44:58 2021 GMT
> *  issuer: C=CN; ST=Some-State; O=Internet Widgits Pty Ltd; CN=localhost
> *  SSL certificate verify result: self signed certificate (18), continuing anyway.
> * Using HTTP2, server supports multi-use
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> * SSL_write() returned SYSCALL, errno = 32
> * Failed sending HTTP2 data
> * nghttp2_session_send() failed: The user callback function failed(-902)
> * Connection #0 to host localhost left intact
> curl: (16) SSL_write() returned SYSCALL, errno = 32

But I want to block the TLS 1.0 and TLS 1.1, only  allow TLS 1.2 and TLS 1,3(As below is a example). how Can I make it work?

> **_curl -vk --tlsv1.0 https://localhost_**
> * Rebuilt URL to: https://localhost/
> *   Trying 127.0.0.1...
> * TCP_NODELAY set
> * Connected to localhost (127.0.0.1) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/certs/ca-certificates.crt
>   CApath: /etc/ssl/certs
> * TLSv1.0 (OUT), TLS handshake, Client hello (1):
> * TLSv1.0 (IN), TLS alert, Server hello (2):
> * _**error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version**_
> * stopped the pause stream!
> * Closing connection 0
> curl: (35) **_error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version_**

**Comment by halverneus** [comment]
Making sure I understand the problem:

- You are using "TLS_MIN_VERS=TLS11".
- When using that variable, TLS1.1 fails and TLS1.2 succeeds.
- The values TLS10, TLS12 and TLS13 work as expected.

If that is true, can you also provide the DEBUG output, please, when using TLS11?

Thank you, again!

**Comment by airbadboy-victor** [comment]
Hi guys, it wired that when we try to use halverneus/static-file-server:test-min-tls in other server. But when I use the command below try to use tlsv1.0, and the server didn't stop the service. 

> C:\Users\username>curl -vk --tlsv1.0 https://hostname:8448
> * Rebuilt URL to: https://hostname:8448/
> *   Trying 10.129.45.107...
> * TCP_NODELAY set
> * Connected to hostname (10.129.45.107) port 8448 (#0)
> * schannel: SSL/TLS connection with hostname port 8448 (step 1/3)
> * schannel: disabled server certificate revocation checks
> * schannel: verifyhost setting prevents Schannel from comparing the supplied target name with the subject names in server certificates.
> * schannel: sending initial handshake data: sending 113 bytes...
> * schannel: sent initial handshake data: sent 113 bytes
> * schannel: SSL/TLS connection with hostname port 8448 (step 2/3)
> * schannel: encrypted data got 2307
> * schannel: encrypted data buffer: offset 2307 length 4096
> * schannel: sending next handshake data: sending 101 bytes...
> * schannel: SSL/TLS connection with hostname port 8448 (step 2/3)
> * schannel: encrypted data got 203
> * schannel: encrypted data buffer: offset 203 length 4096
> * schannel: SSL/TLS handshake complete
> * schannel: SSL/TLS connection with hostname port 8448 (step 3/3)
> * schannel: stored credential handle in session cache
> > GET / HTTP/1.1
> > Host: hostname:8448
> > User-Agent: curl/7.55.1
> > Accept: */*
> > 
> * schannel: client wants to read 102400 bytes
> * schannel: encdata_buffer resized 103424
> * schannel: encrypted data buffer: offset 0 length 103424
> * schannel: encrypted data got 346
> * schannel: encrypted data buffer: offset 346 length 103424
> * schannel: decrypted data length: 1
> * schannel: decrypted data added: 1
> * schannel: decrypted data cached: offset 1 length 102400
> * schannel: encrypted data length: 309
> * schannel: encrypted data cached: offset 309 length 103424
> * schannel: decrypted data length: 283
> * schannel: decrypted data added: 283
> * schannel: decrypted data cached: offset 284 length 102400
> * schannel: encrypted data buffer: offset 0 length 103424
> * schannel: decrypted data buffer: offset 284 length 102400
> * schannel: schannel_recv cleanup
> * schannel: decrypted data returned 284
> * schannel: decrypted data buffer: offset 0 length 102400
> < HTTP/1.1 200 OK
> < Content-Type: text/html; charset=utf-8
> < Last-Modified: Thu, 03 Jun 2021 10:12:33 GMT
> < Date: Tue, 02 Nov 2021 08:00:44 GMT
> < Content-Length: 121
> < 
> <pre>
> <a href="air-gap-gradle-nuget.zip">air-gap-gradle-nuget.zip</a>
> </pre>
> * Connection #0 to host hostname left intact
> 

Do you have other temporary version that maybe I can try about it?

**Comment by halverneus** [comment]
Not, yet. This seems to be an issue in the standard library. I'm actually debating waiting for the issue to be fixed or doing a release with the bug documented (provide warning when using a bugged variable, or only allow the variables that actually work). I'm hoping to get time in the next few days to revisit this. My apologies for letting this issue get cold.

**Comment by airbadboy-victor** [comment]
Hi guy, I am sorry, I think I made a mistake before. I think the halverneus/static-file-server:test-min-tls is not work at all. 
I told you it work on TLS1.0 and TLS1.1 it was not support when I use the halverneus/static-file-server:test-min-tls just because my curl's version was too low. What I update curl's version, TLS1.0 and TLS1.1 can be supported.

> curl -vk --tlsv1.1 https://10.130.15.25:8448
> *   Trying 10.130.15.25:8448...
> * Connected to 10.130.15.25 (10.130.15.25) port 8448 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * TLSv1.0 (OUT), TLS header, Certificate Status (22):
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS header, Certificate Status (22):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS header, Finished (20):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, CERT verify (15):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Finished (20):
> * TLSv1.2 (OUT), TLS header, Finished (20):
> * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * TLSv1.3 (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
> * ALPN, server accepted to use h2
> * Server certificate:
> *  subject: C=CN; ST=Some-State; O=Internet Widgits Pty Ltd; CN=localhost
> *  start date: Jun  4 13:44:58 2021 GMT
> *  expire date: Jul  4 13:44:58 2021 GMT
> *  issuer: C=CN; ST=Some-State; O=Internet Widgits Pty Ltd; CN=localhost
> *  SSL certificate verify result: self-signed certificate (18), continuing anyway.
> * Using HTTP2, server supports multiplexing
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * Using Stream ID: 1 (easy handle 0x1fdac8f18b0)
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> > GET / HTTP/2
> > Host: 10.130.15.25:8448
> > user-agent: curl/7.80.0
> > accept: */*
> >
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> < HTTP/2 200
> < content-type: text/html; charset=utf-8
> < last-modified: Thu, 11 Nov 2021 10:18:40 GMT
> < content-length: 1551
> < date: Thu, 11 Nov 2021 10:20:32 GMT
> <
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> <pre>
> <a href="cacert.pem">cacert.pem</a>
> <a href="cert/">cert/</a>
> <a href="certs/">certs/</a>
> <a href="crl/">crl/</a>
> <a href="curl-curl-7_80_0/">curl-curl-7_80_0/</a>
> <a href="curl-curl-7_80_0.tar.gz">curl-curl-7_80_0.tar.gz</a>
> <a href="envlist">envlist</a>
> <a href="envlist-bak">envlist-bak</a>
> <a href="envlist2">envlist2</a>
> <a href="envlist3">envlist3</a>
> <a href="index.txt">index.txt</a>
> <a href="index.txt.attr">index.txt.attr</a>
> <a href="index.txt.old">index.txt.old</a>
> <a href="manifest.json">manifest.json</a>
> <a href="newcerts/">newcerts/</a>
> <a href="openssl.cnf">openssl.cnf</a>
> <a href="package/">package/</a>
> <a href="private/">private/</a>
> <a href="serial">serial</a>
> <a href="serial.old">serial.old</a>
> <a href="ssl.crt">ssl.crt</a>
> <a href="ssl.key">ssl.key</a>
> <a href="ssl_pri.key">ssl_pri.key</a>
> <a href="static-file-server-master/">static-file-server-master/</a>
> <a href="static-file-server-master.zip">static-file-server-master.zip</a>
> <a href="static-file-server.bak2">static-file-server.bak2</a>
> <a href="static-file-server.tar">static-file-server.tar</a>
> <a href="static-file-server.yml">static-file-server.yml</a>
> <a href="static-file-server.yml.bak">static-file-server.yml.bak</a>
> <a href="static-file-server.yml.bak3">static-file-server.yml.bak3</a>
> <a href="static-file-server2.tar">static-file-server2.tar</a>
> <a href="./static-file-server:test-min-tls.tar">static-file-server:test-min-tls.tar</a>
> <a href="synopsys-detect-6.9.0-air-gap-gradle-nuget.zip">air-gap-gradle-nuget.zip</a>
> </pre>
> * Connection #0 to host 10.130.15.25 left intact

**Comment by airbadboy-victor** [comment]
Hi guy. I think I know why it was wrong. 
First, I mistake use the command curl,  I think is should not used command **_curl -vk --tlsv1.0_**, I should use the command _**curl -vk --tls-max**_ instead. And I should use the latest version of curl( I download the latest version from the link:[](https://curl.se/windows/dl-7.80.0/curl-7.80.0-win64-mingw.zip) , There are still some issues with this version, but it's much better).
Second, I think the source code of function overrideWithEnvVars() in the file config/config.go have a little bit problem.The variable TLSMinValue was missing, so I added the following code inside:

>         TLSMinValue, err := tlsMinVersAsUint16(Get.TLSMinVersStr)
>         if nil == err {
>            Get.TLSMinVers = TLSMinValue
>         } else {
>             log.Printf("Invalid value for '%s': %v\n", Get.TLSMinVersStr, err)
>         }
Please confirm if I am correct. If so, I think you can close the this issue.

**Comment by halverneus** [comment]
I just found the bug. Issue was that, unless a config file was used, `validate()` wasn't being called (`validate()` is the function that was assigning the minimum TLS value). I'm pushing that fix, now (along with a logging addition in the config to assist with future troubleshooting).

**Comment by halverneus** [comment]
@airbadboy-victor , checking in on whether this fix works for you, now.

**Comment by halverneus** [comment]
#63

**Comment by halverneus** [comment]
This feature has been merged and is now included in v1.8.5. If something does not work as expected, please open a new issue.

**Comment by halverneus** [comment]
Glad to help! I think this was a great feature suggestion.
