### ISSUE TITLE
File size limit?

### ISSUE THREAD

**Issue by makejiang** [halverneus/static-file-server#77]
Is there a file size limit?
I got "403 Forbidden" when try to download a 5GB file.

Thanks!

**Comment by halverneus** [comment]
I doubt it is a file size limit (I just tested a 10G file on my system with no issues). I suspect it is more likely a file permissions issue. Can you share how you are running it, the output when ran with DEBUG=true and permissions and owner for the file you are trying to share (I would provide instructions, but I would need to know which OS you are using).

**Comment by makejiang** [comment]
Yes, you are right. Just happened on a big file.

Many thanks!
